components:
  frontend:
    image: fraguinha/livinvicta.com-frontend:latest@sha256:a883db152c4d183bf086b0ddbd25f2c036b870e7eafd3e48aff2210802c37a02 # {"$imagepolicy": "flux-system:livinvicta-frontend-policy"}
    port: 8080
    replicaCount: 2
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 40Mi
  backend:
    image: fraguinha/livinvicta.com-backend:latest@sha256:021876ede4341e2dd7664a0b828206f011b2ca98d0853d496204f649d94123f1 # {"$imagepolicy": "flux-system:livinvicta-backend-policy"}
    port: 8080
    replicaCount: 2
    env:
      - name: PORT
        value: "8080"
      - name: NODE_ENV
        value: production
      - name: DATABASE
        valueFrom:
          secretKeyRef:
            name: livinvicta-secrets
            key: DATABASE
      - name: SECRET
        valueFrom:
          secretKeyRef:
            name: livinvicta-secrets
            key: SECRET
      - name: GOOGLE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: livinvicta-secrets
            key: GOOGLE_CLIENT_ID
      - name: GOOGLE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: livinvicta-secrets
            key: GOOGLE_CLIENT_SECRET
    resources:
      requests:
        cpu: 5m
        memory: 64Mi
      limits:
        memory: 96Mi
ingress:
  className: traefik
  clusterIssuer: letsencrypt
  externalDnsTarget: ""
  hosts:
    - livinvicta.com
    - www.livinvicta.com
    - livinvicta.pt
    - www.livinvicta.pt
  paths:
    - path: /api
      pathType: Prefix
      component: backend
    - path: /
      pathType: Prefix
      component: frontend
  tls:
    secretName: livinvicta-tls-secret
