services:
  backend:
    image: fraguinha/livinvicta.com-backend:latest
    container_name: livinvicta-backend
    environment:
      - NODE_ENV
      - DATABASE
      - SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET

  frontend:
    image: fraguinha/livinvicta.com-frontend:latest
    container_name: livinvicta-frontend
    depends_on:
      - backend

  proxy:
    image: fraguinha/livinvicta.com-proxy:latest
    container_name: livinvicta-proxy
    ports:
      - "8081:80"
    depends_on:
      - backend
      - frontend
