version: "3.8"
services:
  backend:
    build: ./src/backend
    ports:
      - "8081:8080"
    volumes:
      - ./src/backend/images:/app/images
    environment:
      - NODE_ENV=production

  frontend:
    build: ./src/frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
