apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- if .Values.ingress.externalDnsTarget }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.externalDnsTarget | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $.Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .component }}
                port:
                  number: {{ (index $.Values.components .component).port }}
          {{- end }}
    {{- end }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
