apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: livinvicta
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fraguinha/livinvicta.com-backend:latest@sha256:1d712395a7c2bace3f1df4829d8ddf3e2be590abb490b3cac1d0205086eee5af # {"$imagepolicy": "flux-system:livinvicta-backend-policy"}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: DATABASE
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: GOOGLE_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: livinvicta
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
