apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: livinvicta
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fraguinha/livinvicta.com-backend:latest@sha256:021876ede4341e2dd7664a0b828206f011b2ca98d0853d496204f649d94123f1 # {"$imagepolicy": "flux-system:livinvicta-backend-policy"}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              memory: 96Mi
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: DATABASE
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: livinvicta-secrets
                  key: GOOGLE_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: livinvicta
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
