name: Docker

on:
  push:
    branches:
      - main
    paths:
      - "src/frontend/**"
      - "src/backend/**"
      - ".github/workflows/docker.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: fraguinha/livinvicta.com-backend:latest
          context: ./src/backend
          file: ./src/backend/Dockerfile

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: fraguinha/livinvicta.com-frontend:latest
          context: ./src/frontend
          file: ./src/frontend/Dockerfile

      - name: Build and push proxy image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: fraguinha/livinvicta.com-proxy:latest
          context: ./src/proxy
          file: ./src/proxy/Dockerfile
